### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by jgarte** [litcave/neatmail#1]
Hi, what is the license for this project?

Public Domain?

I ask because I'm looking to package it for [guix](guix.gnu.org).

**Comment by aligrudi** [comment]
Hi,

jgart ***@***.***> wrote:
> Hi, what is the license for this project?
> 
> Public Domain?

It is under ISC, included in the comments of mail.c.

	Ali

**Comment by jgarte** [comment]
Thanks! I'll close
