### ISSUE TITLE
Darwin fails

### ISSUE THREAD

**Issue by polluks** [litcave/neatmail#4]
test/07.sh hangs and...
```
$ mv test/07.sh .
$ make check
/bin/sh test.sh
test/00.sh: OK
test/01.sh: OK
test/02.sh: OK
test/03.sh: OK
test/04.sh: OK
test/05.sh: OK
test/06.sh: OK
test/08.sh: OK
test/09.sh: OK
test/10.sh: OK
test/11.sh: OK
test/12.sh: OK
test/13.sh: OK
test/20.sh: OK
test/21.sh: OK
test/22.sh: OK
test/23.sh: Failed
--- ./test/23.out	2023-05-20 17:53:45
+++ /tmp/.neatmail.out	2023-05-20 18:10:24
@@ -1,9 +0,0 @@
-From root Tue Dec 22 02:02:02 2015
-From: B <b@b.eu>
-To: A <a@a.eu>
-Subject: Message from B
-Message-Id: <msg002>
-Date: Tue, 22 Dec 2015 02:02:00 +0100
-
-This is B.
-
make: *** [check] Error 1

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> test/07.sh hangs and...

I guess the problem is with this Neatmail command:

  :1ft "sed 's/B/X/g'"

Does it work when you try it manually?

> ```
> test/23.sh: Failed

I am not sure why this fails.  Would you try the commands in
test/23.sh to see which of them is not working properly?

Thanks,
Ali

**Comment by polluks** [comment]
`:1ft` hangs, at least `sed 's/B/X/g' </tmp/.neatmail.mbox` works.

After 23.sh:
```
-rw-r--r--  1 polluks  wheel  504 20 Mai 18:10 /tmp/.neatmail.mbox
-rw-r--r--  1 polluks  wheel  607 22 Mai 00:37 /tmp/.nmtest.box
-rw-r--r--  1 polluks  wheel    0 22 Mai 00:49 /tmp/.neatmail.out

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> `:1ft` hangs, at least `sed 's/B/X/g' </tmp/.neatmail.mbox` works.
> 
> After 23.sh:
> ```
> -rw-r--r--  1 polluks  wheel  504 20 Mai 18:10 /tmp/.neatmail.mbox
> -rw-r--r--  1 polluks  wheel  607 22 Mai 00:37 /tmp/.nmtest.box

Thanks.  Does the following patch fix the problem?

	Ali

diff --git a/util.c b/util.c
index 084061f..13326ee 100644
--- a/util.c
+++ b/util.c
@@ -102,18 +102,26 @@ int xpipe(char *cmd, char *ibuf, long ilen, char **obuf, long *olen)
 			int ret = read(fds[0].fd, buf, sizeof(buf));
 			if (ret > 0)
 				sbuf_mem(sb, buf, ret);
-			if (ret < 0)
+			if (ret <= 0) {
 				close(fds[0].fd);
-		} else if (fds[0].revents & (POLLERR | POLLHUP | POLLNVAL)) {
-			fds[0].fd = -1;
+				fds[0].fd = -1;
+			}
+			continue;
 		}
 		if (fds[1].revents & POLLOUT) {
 			int ret = write(fds[1].fd, ibuf + nw, ilen - nw);
 			if (ret > 0)
 				nw += ret;
-			if (ret <= 0 || nw == ilen)
+			if (ret <= 0 || nw == ilen) {
 				close(fds[1].fd);
-		} else if (fds[1].revents & (POLLERR | POLLHUP | POLLNVAL)) {
+				fds[1].fd = -1;
+			}
+			continue;
+		}
+		if (fds[0].revents & (POLLERR | POLLHUP | POLLNVAL)) {
+			fds[0].fd = -1;
+		}
+		if (fds[1].revents & (POLLERR | POLLHUP | POLLNVAL)) {
 			fds[1].fd = -1;
 		}
 	}

**Comment by polluks** [comment]
Better, 07 is fixed, 23 is still broken.

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> Better, 07 is fixed, 23 is still broken.

What does this return:

  $ ./mail pn -H -s0 test/test.mbox

Ali

**Comment by polluks** [comment]
```
From root Tue Dec 21 01:01:01 2015
From: A <a@a.eu>
To: B <b@b.eu>
Subject: Message from A
Message-Id: <msg001>
Date: Tue, 21 Dec 2015 01:01:00 +0100
Neatmail-Source: 0@test/test.mbox 0 163

From root Tue Dec 22 02:02:02 2015
From: B <b@b.eu>
To: A <a@a.eu>
Subject: Message from B
Message-Id: <msg002>
Date: Tue, 22 Dec 2015 02:02:00 +0100
Neatmail-Source: 1@test/test.mbox 163 326

From root Tue Dec 23 03:03:03 2015
From: C <c@c.eu>
To: A <a@a.eu>
Cc: B <b@b.eu>
Subject: Message from C
Message-Id: <msg003>
Date: Tue, 23 Dec 2015 03:03:00 +0100
Neatmail-Source: 2@test/test.mbox 326 504

test/test.mbox: 3 messages

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> ```
> >From root Tue Dec 21 01:01:01 2015
> From: A ***@***.***>
> To: B ***@***.***>
> Subject: Message from A
> Message-Id: <msg001>
> Date: Tue, 21 Dec 2015 01:01:00 +0100
> Neatmail-Source: ***@***.***/test.mbox 0 163

The output seems correct.  How about this:

  ./mail pn -H -s0 test/text.mbox >x.box
  ./mail pg -s x.box 1

	Ali

**Comment by polluks** [comment]
Option s seems to fail
```
$ ./mail pn -H -s0 test/test.mbox >x.box
test/test.mbox: 3 messages
$ ./mail pg -s x.box 1                  
$ echo $?                               
1

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> $ ./mail pn -H -s0 test/test.mbox >x.box
> test/test.mbox: 3 messages
> $ ./mail pg -s x.box 1                  
> $ echo $?                               
> 1

Thank you very much.  This patch may reveal the reason for
this failure.

	Ali

diff --git a/pg.c b/pg.c
index f874f40..9c999ee 100644
--- a/pg.c
+++ b/pg.c
@@ -165,9 +165,9 @@ int pg(char *argv[])
 				hdr++;
 			free(msg);
 			if (sscanf(hdr, "%d@%s %ld %ld", &num, box, &beg, &end) != 4)
-				return 1;
+				return 2;
 			if (mbox_off(box, beg, end, &msg, &msglen) != 0)
-				return 1;
+				return 3;
 		}
 		if (demime && !msg_demime(msg, msglen, &mod, &modlen)) {
 			free(msg);

**Comment by polluks** [comment]
I see, it's return 2 because hdr is empty.
```
Process 65385 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 2.1 3.1
    frame #0: 0x00000001000096b8 mail`pg(argv=0x000000016fdff4f8) at pg.c:166:9
   163 			if (source && (hdr = msg_get(msg, msglen, "Neatmail-Source:")) != NULL) {
   164 				while (*hdr && *hdr != ' ')
   165 					hdr++;
-> 166 				free(msg);
   167 				if (sscanf(hdr, "%d@%s %ld %ld", &num, box, &beg, &end) != 4)
   168 					return 2;
   169 				if (mbox_off(box, beg, end, &msg, &msglen) != 0)
Target 0: (mail) stopped.
(lldb) p hdr
(char *) $17 = 0x00006000039000a6 " 1@test/test.mbox 163 326\n\n"
(lldb) s
Process 65385 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
    frame #0: 0x00000001000096c0 mail`pg(argv=0x000000016fdff4f8) at pg.c:167:15
   164 				while (*hdr && *hdr != ' ')
   165 					hdr++;
   166 				free(msg);
-> 167 				if (sscanf(hdr, "%d@%s %ld %ld", &num, box, &beg, &end) != 4)
   168 					return 2;
   169 				if (mbox_off(box, beg, end, &msg, &msglen) != 0)
   170 					return 3;
Target 0: (mail) stopped.
(lldb) p hdr
(char *) $18 = 0x00006000039000a6 ""

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> I see, it's return 2 because hdr is empty.

Very good.

Is hdr empty?
If not, I suspect that the sscanf call does not work as expected.
Does the following program print 4?

```
#include <stdio.h>

int main(void)
{
	char box[512];
	int num;
	long beg, end;
	int x = ***@***.*** 1000 2000", "%d@%s %ld %ld", &num, box, &beg, &end);
	printf("%d\n", x);
	return 0;
}
```

Ali

**Comment by polluks** [comment]
```c
#include <stdio.h>

int main(void)
{
char box[512];
int num;
long beg, end;
int x = sscanf("1@***.*** 1000 2000", "%d@%s %ld %ld", &num, box, &beg, &end);
printf("%d\n", x);
return 0;
}
```
The scan works, it's the free! See my debugger log.

**Comment by aligrudi** [comment]
Stefan ***@***.***> wrote:
> The scan works, it's the free! See my debugger log.

Sorry.  The debugger log was not included in the email I received from
Github.

I have just pushed a fix.  Does it work now?

	Ali

**Comment by polluks** [comment]
My fault, I tried lldb later. There's no new push so far...

**Comment by polluks** [comment]
It works like a charm...
